# Generated by Django 5.1.6 on 2026-03-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        # Cliente
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),

        # Quarto
        migrations.AddField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='capacidade',
            field=models.IntegerField(default=2, verbose_name='Capacidade de Hóspedes'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),

        # Reserva
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),

        # Despesa
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('LIMPEZA', 'Limpeza'), ('MANUTENCAO', 'Manutenção'), ('ALIMENTACAO', 'Alimentação'), ('UTILITARIOS', 'Utilitários'), ('FOLHA', 'Folha de Pagamento'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),

        # Receita
        migrations.AddField(
            model_name='receita',
            name='origem',
            field=models.CharField(choices=[('RESERVA', 'Reserva'), ('SERVICO', 'Serviço Adicional'), ('EVENTO', 'Evento'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='receita',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),
    ]
